[package]
name = "badlang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5.2"
clap = { version = "4.4.3", features = ["derive"] }
colored = "2.0.4"
fastrand = "2.0.0"
geocoding = "0.4.0"
geolocation = "0.2.1"
humansize = "2.1.3"
indicatif = "0.17.7"
inquire = "0.6.2"
local-ip-address = "0.5.5"
notify-rust = "4.9.0"
open = "5.0.0"
rand = "0.8.5"
reqwest = "0.11.20"
savefile = "0.16.2"
savefile-derive = "0.16.2"
strum = "0.25.0"
strum_macros = "0.25.2"
tokio = "1.32.0"
