error_on_line_overflow = true
# error_on_unformatted = true
max_width = 200
combine_control_expr = false
wrap_comments = true
comment_width = 75
enum_discrim_align_threshold = 50
struct_field_align_threshold = 50
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
edition = "2021"
