[package]
name = "edge-function"
version = "0.1.0"
edition = "2021"
authors = [ "gianzellweger <gian.zellweger@ict-scouts.ch>" ]

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version="0.2.0" }
worker-macros = { version="0.2.0" }
console_error_panic_hook = { version = "0.1.1" }
tokio = { version = "1.38.0", features = ["time"] }
