name: Deploy (Linux)

on:
    push:
        branches: [ "release" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
        - name: Install Dependencies
          run: sudo apt-get install -y libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
        - name: Deploy
          run: cargo publish
